import type { BootstrapPayload } from './types';

export const mockBootstrap: BootstrapPayload = {
  items: [
    {
      id: 'item-1',
      type: 'markdown',
      title: 'Launch checklist for the desktop release',
      textContent:
        '# Launch checklist\n\n- Finalize icon exports\n- Verify offline OCR\n- Run packaging smoke tests',
      richText: '',
      filePath: '',
      storagePath: '',
      sourceApp: 'Notes',
      hash: 'a',
      copyCount: 4,
      favorite: true,
      ocrText: '',
      metadata: '{}',
      preview: {
        kind: 'markdown',
        summary: 'Launch checklist with release tasks',
        body: '# Launch checklist\n\n- Finalize icon exports\n- Verify offline OCR\n- Run packaging smoke tests',
        thumbnailPath: '',
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      lastCopiedAt: new Date().toISOString(),
    },
    {
      id: 'item-2',
      type: 'json',
      title: 'Settings payload',
      textContent: '{"theme":"graphite","ocrEnabled":true,"historyLimit":0}',
      richText: '',
      filePath: '',
      storagePath: '',
      sourceApp: 'Terminal',
      hash: 'b',
      copyCount: 1,
      favorite: false,
      ocrText: '',
      metadata: '{}',
      preview: {
        kind: 'json',
        summary: 'JSON settings payload',
        body: '{\n  "theme": "graphite",\n  "ocrEnabled": true,\n  "historyLimit": 0\n}',
        thumbnailPath: '',
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      lastCopiedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    },
    {
      id: 'item-3',
      type: 'url',
      title: 'https://wails.io',
      textContent: 'https://wails.io',
      richText: '',
      filePath: '',
      storagePath: '',
      sourceApp: 'Arc',
      hash: 'c',
      copyCount: 2,
      favorite: false,
      ocrText: '',
      metadata: '{}',
      preview: {
        kind: 'url',
        summary: 'Wails framework homepage',
        body: 'https://wails.io',
        thumbnailPath: '',
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      lastCopiedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    },
  ],
  settings: {
    launchOnBoot: false,
    theme: 'graphite',
    globalShortcut: 'Ctrl+Shift+Space',
    historyLimit: 0,
    ocrEnabled: true,
    privateMode: false,
    pauseHistory: false,
    ignoreApplications: ['1Password', 'Bitwarden'],
    storageDirectory: '~/.glyph',
    largeText: false,
    highContrast: false,
  },
};
